"""
Generates a PAC-2024-style accessibility report PDF using ReportLab.
Layout constants are grouped at the top for easy styling adjustments.
"""
from io import BytesIO
from datetime import datetime

# ── Layout constants ────────────────────────────────────────────────────────
COLOUR_GREEN  = (0.18, 0.64, 0.18)
COLOUR_RED    = (0.83, 0.18, 0.18)
COLOUR_GREY   = (0.55, 0.55, 0.55)
COLOUR_DARK   = (0.10, 0.10, 0.10)
COLOUR_BG     = (0.97, 0.97, 0.97)
COLOUR_HEADER = (0.02, 0.30, 0.59)   # TD blue

FONT_TITLE  = 16
FONT_H2     = 12
FONT_BODY   = 9
FONT_SMALL  = 7.5

PAGE_MARGIN = 40
# ────────────────────────────────────────────────────────────────────────────


def build_pac_report(results: list[dict], filename: str) -> bytes:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import mm
    from reportlab.pdfgen import canvas
    from reportlab.lib.colors import HexColor, Color

    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    def rgb(t):
        return Color(t[0], t[1], t[2])

    passed  = [r for r in results if r["status"] == "pass"]
    failed  = [r for r in results if r["status"] == "fail"]
    na      = [r for r in results if r["status"] == "na"]

    # ── Cover / header ───────────────────────────────────────────────────────
    c.setFillColor(rgb(COLOUR_HEADER))
    c.rect(0, height - 80, width, 80, fill=1, stroke=0)

    c.setFillColor(rgb((1, 1, 1)))
    c.setFont("Helvetica-Bold", FONT_TITLE)
    c.drawString(PAGE_MARGIN, height - 40, "PDF Accessibility Checker — Test Report")

    c.setFont("Helvetica", FONT_BODY)
    c.drawString(PAGE_MARGIN, height - 58,
                 f"File: {filename}    |    Checked: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}")
    c.drawString(PAGE_MARGIN, height - 70,
                 "Standard: ISO 14289-1 (PDF/UA)  |  Matterhorn Protocol 1.1")

    # ── Summary box ─────────────────────────────────────────────────────────
    summary_y = height - 130
    box_w = (width - PAGE_MARGIN * 2 - 20) / 3

    for i, (label, count, colour) in enumerate([
        ("Passed", len(passed), COLOUR_GREEN),
        ("Failed", len(failed), COLOUR_RED),
        ("Not Applicable", len(na), COLOUR_GREY),
    ]):
        x = PAGE_MARGIN + i * (box_w + 10)
        c.setFillColor(rgb(colour))
        c.roundRect(x, summary_y - 40, box_w, 45, 4, fill=1, stroke=0)
        c.setFillColor(rgb((1, 1, 1)))
        c.setFont("Helvetica-Bold", 18)
        c.drawCentredString(x + box_w / 2, summary_y - 15, str(count))
        c.setFont("Helvetica", FONT_SMALL)
        c.drawCentredString(x + box_w / 2, summary_y - 32, label)

    # ── Results table ────────────────────────────────────────────────────────
    y = summary_y - 70
    c.setFont("Helvetica-Bold", FONT_H2)
    c.setFillColor(rgb(COLOUR_DARK))
    c.drawString(PAGE_MARGIN, y, "Detailed Results")
    y -= 18

    c.setFillColor(rgb(COLOUR_HEADER))
    c.rect(PAGE_MARGIN, y - 2, width - PAGE_MARGIN * 2, 14, fill=1, stroke=0)
    c.setFillColor(rgb((1, 1, 1)))
    c.setFont("Helvetica-Bold", FONT_SMALL)
    c.drawString(PAGE_MARGIN + 4, y + 3, "ID")
    c.drawString(PAGE_MARGIN + 55, y + 3, "Checkpoint")
    c.drawString(width - PAGE_MARGIN - 45, y + 3, "Status")
    y -= 16

    for result in results:
        if y < 60:
            c.showPage()
            y = height - PAGE_MARGIN

        status = result.get("status", "na")
        colour = {"pass": COLOUR_GREEN, "fail": COLOUR_RED, "na": COLOUR_GREY}.get(status, COLOUR_GREY)
        label  = {"pass": "PASS", "fail": "FAIL", "na": "N/A"}.get(status, "N/A")

        row_h = 24 if status == "fail" else 16
        c.setFillColor(rgb(COLOUR_BG))
        c.rect(PAGE_MARGIN, y - row_h + 4, width - PAGE_MARGIN * 2, row_h, fill=1, stroke=0)

        c.setFillColor(rgb(COLOUR_DARK))
        c.setFont("Helvetica", FONT_SMALL)
        c.drawString(PAGE_MARGIN + 4, y - 4, result.get("id", ""))

        desc = result.get("plain_english", "")[:90]
        c.drawString(PAGE_MARGIN + 55, y - 4, desc)

        c.setFillColor(rgb(colour))
        c.roundRect(width - PAGE_MARGIN - 44, y - row_h + 6, 40, 12, 3, fill=1, stroke=0)
        c.setFillColor(rgb((1, 1, 1)))
        c.setFont("Helvetica-Bold", FONT_SMALL)
        c.drawCentredString(width - PAGE_MARGIN - 24, y - 1, label)

        if status == "fail":
            c.setFillColor(rgb(COLOUR_RED))
            c.setFont("Helvetica-Oblique", FONT_SMALL - 0.5)
            fix = result.get("fix_hint", "")[:100]
            c.drawString(PAGE_MARGIN + 55, y - 14, f"Fix: {fix}")

        y -= row_h + 4

    # ── Footer ───────────────────────────────────────────────────────────────
    c.setFont("Helvetica", FONT_SMALL - 0.5)
    c.setFillColor(rgb(COLOUR_GREY))
    c.drawString(PAGE_MARGIN, 20, "Generated by TD Accessibility Checker  |  ISO 14289-1 / Matterhorn Protocol 1.1")

    c.save()
    return buffer.getvalue()
